version: "3.9"

# Docker Reference: https://docs.docker.com/engine/reference/builder/

services:
  db:
    # Docker Hub Reference: https://hub.docker.com/_/mysql/
    image: mysql
    restart: always
    environment:
      MYSQL_HOST: db
      MYSQL_DATABASE: plant_health
      MYSQL_RANDOM_ROOT_PASSWORD: yes
      MYSQL_USER: spring
      MYSQL_PASSWORD: password
    networks:
      - db-network
    command: --default-authentication-plugin=mysql_native_password
    expose: [3306]
    healthcheck:
      test: ["CMD", "mysqladmin", "-u $$MYSQL_USER", "-p $$MYSQL_PASSWORD" ,"ping", "-h", "localhost"]
      timeout: 5s
      retries: 20
  # -----------------------------------------------------------------------------
  # -----------------------------------------------------------------------------
  spring:
    build:
      dockerfile: ./Dockerfile
      context: ./backend
    depends_on:
      db:
        condition: service_healthy
    restart: always
    links:
      - db
      - db:database
    ports:
      - "8443:8080"
    expose: [8443]
    networks:
      - api-network
      - db-network
  # -----------------------------------------------------------------------------
  # -----------------------------------------------------------------------------
  sveltekit:
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
    depends_on:
      - spring
    restart: always
    networks:
      - api-network
    ports:
      - "3000:3000"
    expose: [3000]
  # -----------------------------------------------------------------------------
  # -----------------------------------------------------------------------------
  adminer:
    image: adminer
    restart: always
    depends_on:
      - db
    networks:
      - db-network
    ports:
      - "8081:8080"
    profiles:
      - test

networks:
  default:
    driver: none
  db-network: {}
  api-network: {}
