swa:
  token:
    expiration-duration: 1d
  api:
    base: /api

server:
  port: 8080
  servlet:
    context-path: /

logging:
  level:
    web: INFO

springdoc:
  # Disable Swagger in Production
  api-docs:
    path: /api-docs
    enabled: false
  swagger-ui:
    path: /swagger
    enabled: false

spring:
  profiles:
    active: "prod"
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://db:3306/plant_health
    username: spring
    password: password
  jpa:
    hibernate:
      # Create Model Tables on Startup
      ddl-auto: update
  web:
    resources:
      # Disable static Resource Mapping
      add-mappings: false
